source 'https://rubygems.org'

gem 'sinatra'
# gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'pg'
gem 'puma', ">= 4.3.3"
gem 'faker'
gem 'rack-test'
gem 'bcrypt'
gem 'rake', '> 12.0'
gem 'require_all'
gem 'json'
gem 'bootstrap', '4.3.1'
gem 'sinatra-flash'
gem 'rack-timeout'
gem 'activerecord-import'
gem 'sinatra-contrib'
# gem 'sinatra-contrib', require: false
gem 'sinatra-partial'